addSbtPlugin("com.jsuereth"      % "sbt-pgp"                % "2.0.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"            % "1.0.13")
addSbtPlugin("com.typesafe"      % "sbt-mima-plugin"        % "0.7.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"           % "2.4.3")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"          % "1.6.1")
addSbtPlugin("io.chrisdavenport" % "sbt-mima-version-check" % "0.1.2")
