addSbtPlugin("com.github.sbt"    % "sbt-pgp"                % "2.1.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"            % "1.0.13")
addSbtPlugin("com.typesafe"      % "sbt-mima-plugin"        % "0.9.2")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"           % "2.4.5")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"          % "1.8.2")
addSbtPlugin("io.chrisdavenport" % "sbt-mima-version-check" % "0.1.2")
