addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "2.0.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.13")
addSbtPlugin("com.typesafe"      % "sbt-mima-plugin" % "0.6.4")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"    % "2.3.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"   % "1.6.1")
